/* This file was generated by $0.  Do not edit manually.  */
package net.opentsdb;

/** Build data for {@code $PACKAGE} */
public final class BuildData {
  /** Version string MAJOR.MINOR.MAINT */
  public static final String version = "$VERSION";
  /** Short revision at which this package was built. */
  public static final String short_revision = "$short_rev";
  /** Full revision at which this package was built. */
  public static final String full_revision = "$full_rev";
  /** UTC date at which this package was built. */
  public static final String date = "$date";
  /** UNIX timestamp of the time of the build. */
  public static final long timestamp = 0;

  /** Represents the status of the repository at the time of the build. */
  public static enum RepoStatus {
    /** The status of the repository was unknown at the time of the build. */
    UNKNOWN,
    /** There was no local modification during the build. */
    MINT,
    /** There were some local modifications during the build. */
    MODIFIED;
  }
  /** Status of the repository at the time of the build. */
  public static final RepoStatus repo_status = RepoStatus.MODIFIED;

  /** Username of the user who built this package. */
  public static final String user = "$user";
  /** Host on which this package was built. */
  public static final String host = "$host";
  /** Path to the repository in which this package was built. */
  public static final String repo = "$repo";

  /** Human readable string describing the revision of this package. */
  public static final String revisionString() {
    return "$PACKAGE $VERSION built at revision $short_rev ($repo_status)";
  }
  /** Human readable string describing the build information of this package. */
  public static final String buildString() {
    return "Built on $date by $user@$host:$repo";
  }

  // These functions are useful to avoid cross-jar inlining.

  /** Version string MAJOR.MINOR.MAINT */
  public static String version() {
    return version;
  }
  /** Short revision at which this package was built. */
  public static String shortRevision() {
    return short_revision;
  }
  /** Full revision at which this package was built. */
  public static String fullRevision() {
    return full_revision;
  }
  /** UTC date at which this package was built. */
  public static String date() {
    return date;
  }
  /** UNIX timestamp of the time of the build. */
  public static long timestamp() {
    return timestamp;
  }
  /** Status of the repository at the time of the build. */
  public static RepoStatus repoStatus() {
    return repo_status;
  }
  /** Username of the user who built this package. */
  public static String user() {
    return user;
  }
  /** Host on which this package was built. */
  public static String host() {
    return host;
  }
  /** Path to the repository in which this package was built. */
  public static String repo() {
    return repo;
  }

  // Can't instantiate.
  private BuildData() {}
}